#!/usr/bin/env bash
# gen-study-index.sh — regenerates the study-notes index (study-notes/README.md)
# deterministically from every note file in this repo's study-notes/ directory
# (Plan 08). Mirrors gen-adr-index.sh's shape exactly (ADR-0001's own
# generated-never-hand-edited pattern, extended here to study notes).
#
# Walks study-notes/*.md, excluding _template.md and README.md itself, sorted
# ascending by slug (the filename, with no numeric prefix — study notes are
# not sequentially numbered the way ADRs are; the slug alone is the stable
# sort key and the stable link target). A directory with zero real notes
# (only the template present) still gets an explicit "no study notes yet"
# section — a silently-empty table is indistinguishable from a section
# nobody checked. Output has no timestamp, no hostname, and no
# directory-order dependence, so running this twice produces byte-identical
# output.
#
# Usage:
#   scripts/gen-study-index.sh            # writes study-notes/README.md (default)
#   scripts/gen-study-index.sh <out-file> # writes to <out-file> instead
#                                          # (used by check-study-notes.sh's
#                                          # freshness check, so that check
#                                          # never has a side effect on the
#                                          # committed index)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_ROOT="$(dirname "${SCRIPT_DIR}")"                    # estate/athena-docs
STUDY_DIR="${DOCS_ROOT}/study-notes"
OUT_FILE="${1:-${STUDY_DIR}/README.md}"

ORG="AuraBit"

extract_field() {
  # extract_field <file> <field-name>
  grep -m1 -E "^\* $2:" "$1" 2>/dev/null | sed -E "s/^\* $2:[[:space:]]*//"
}

# ADR field values may wrap and continue with a two-space-indented
# continuation line (see the template's own multi-line examples) — collapse
# any such continuation onto the field's own line before extracting.
extract_field_joined() {
  # extract_field_joined <file> <field-name>
  awk -v field="$2" '
    BEGIN { on=0 }
    $0 ~ "^\\* " field ":" { on=1; sub("^\\* " field ":[[:space:]]*", ""); line=$0; next }
    on && /^  / { sub(/^  */, " "); line=line $0; next }
    on { print line; on=0 }
    END { if (on) print line }
  ' "$1"
}

resolve_adr_link() {
  # resolve_adr_link <adr-path-relative-to-estate-root>
  # Returns a markdown link target: a relative path if inside this repo
  # (athena-docs/...), a github.com blob URL otherwise. A returned relative
  # path is relative to study-notes/ — this generator's output always lives
  # at study-notes/README.md, one directory below the repo root where
  # athena-docs/docs/adr/ actually is, so the same-repo branch must hop up
  # one directory. The "../" prefix is a literal constant, never derived
  # from OUT_FILE/$PWD/realpath: check-study-notes.sh's freshness check runs
  # this generator against a mktemp path under /tmp and diffs the result
  # byte-for-byte against the committed index, so an output-path-derived
  # prefix would render differently there and break that check permanently.
  local path="$1"
  case "${path}" in
    athena-docs/*)
      printf '../%s' "${path#athena-docs/}"
      ;;
    */*)
      local repo="${path%%/*}"
      local rest="${path#*/}"
      printf 'https://github.com/%s/%s/blob/main/%s' "${ORG}" "${repo}" "${rest}"
      ;;
    *)
      printf '%s' "${path}"
      ;;
  esac
}

{
  echo "# Study Notes Index"
  echo
  echo "Generated by \`scripts/gen-study-index.sh\` from every file in \`study-notes/\` — do not hand-edit this file; regenerate it and commit the result instead. See [_template.md](_template.md) for the five-section format every note below follows."
  echo

  files=()
  if [ -d "${STUDY_DIR}" ]; then
    while IFS= read -r f; do
      files+=("${f}")
    done < <(LC_ALL=C find "${STUDY_DIR}" -maxdepth 1 -type f -name '*.md' ! -name '_template.md' ! -name 'README.md' | LC_ALL=C sort)
  fi

  if [ "${#files[@]}" -eq 0 ]; then
    echo "_No study notes yet._"
    echo
  else
    echo "| Note | Tool | Summary | Related ADRs |"
    echo "|------|------|---------|--------------|"
    for f in "${files[@]}"; do
      base="$(basename "${f}")"
      slug="${base%.md}"
      tool="$(extract_field "${f}" "Tool")"
      summary="$(extract_field "${f}" "Summary")"
      adrs_raw="$(extract_field_joined "${f}" "Related ADRs")"

      adr_links=""
      IFS=',' read -ra adr_parts <<< "${adrs_raw}"
      for part in "${adr_parts[@]}"; do
        part="$(printf '%s' "${part}" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
        [ -z "${part}" ] && continue
        adr_base="$(basename "${part}")"
        link="$(resolve_adr_link "${part}")"
        if [ -z "${adr_links}" ]; then
          adr_links="[${adr_base}](${link})"
        else
          adr_links="${adr_links}, [${adr_base}](${link})"
        fi
      done

      echo "| [${slug}](${base}) | ${tool} | ${summary} | ${adr_links} |"
    done
    echo
  fi
} > "${OUT_FILE}"

echo "Wrote ${OUT_FILE}"
