#!/usr/bin/env bash
# gen-adr-index.sh — regenerates the master ADR index (docs/adr/README.md)
# deterministically across all four estate repositories (ADR-0001).
#
# Walks a fixed, ordered list of the four estate repositories, resolving
# sibling repos relative to this repo's own location on disk (the estate/
# layout: all four repos are siblings). A repository whose docs/adr/
# directory is absent (or empty) still gets an explicit "no ADRs yet"
# section — a silently-omitted section is indistinguishable from a section
# nobody checked. Output has no timestamp, no hostname, and no
# directory-order dependence, so running this twice produces byte-identical
# output.
#
# Usage:
#   scripts/gen-adr-index.sh            # writes docs/adr/README.md (default)
#   scripts/gen-adr-index.sh <out-file> # writes to <out-file> instead
#                                        # (used by check-adr-hygiene.sh's
#                                        # freshness check, so that check
#                                        # never has a side effect on the
#                                        # committed index)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_ROOT="$(dirname "${SCRIPT_DIR}")"           # estate/athena-docs
ESTATE_ROOT="$(dirname "${DOCS_ROOT}")"          # estate/
OUT_FILE="${1:-${DOCS_ROOT}/docs/adr/README.md}"

# The org login is a fixed constant, not read from the environment or the
# network, so the generator's output stays deterministic and offline-safe.
ORG="AuraBit"

# Fixed, deterministic repository order — never derived from directory
# listing order.
REPOS=(athena-app athena-infra athena-gitops athena-docs)

repo_adr_dir() {
  case "$1" in
    athena-docs) printf '%s' "${DOCS_ROOT}/docs/adr" ;;
    *) printf '%s' "${ESTATE_ROOT}/$1/docs/adr" ;;
  esac
}

extract_field() {
  # extract_field <file> <field-name>
  grep -m1 -E "^\* $2:" "$1" 2>/dev/null | sed -E "s/^\* $2:[[:space:]]*//"
}

extract_title() {
  # First "# NNNN. Title" heading, title with the number prefix stripped.
  grep -m1 -E '^# [0-9]{4}\.' "$1" | sed -E 's/^# [0-9]{4}\.[[:space:]]*//'
}

{
  echo "# ADR Index"
  echo
  echo "Generated by \`scripts/gen-adr-index.sh\` from every repository's \`docs/adr/\` directory — do not hand-edit this file; regenerate it and commit the result instead. See [ADR-0001](0001-how-we-record-decisions.md) for the rules every entry below follows."
  echo

  for repo in "${REPOS[@]}"; do
    echo "## ${repo}"
    echo

    adr_dir="$(repo_adr_dir "${repo}")"
    files=()
    if [ -d "${adr_dir}" ]; then
      while IFS= read -r f; do
        files+=("${f}")
      done < <(LC_ALL=C find "${adr_dir}" -maxdepth 1 -type f -name '[0-9][0-9][0-9][0-9]-*.md' | LC_ALL=C sort)
    fi

    if [ "${#files[@]}" -eq 0 ]; then
      echo "_No ADRs yet._"
      echo
      continue
    fi

    echo "| ADR | Title | Status | Tier |"
    echo "|-----|-------|--------|------|"
    for f in "${files[@]}"; do
      base="$(basename "${f}")"
      title="$(extract_title "${f}")"
      status="$(extract_field "${f}" "Status")"
      tier="$(extract_field "${f}" "Tier")"
      if [ "${repo}" = "athena-docs" ]; then
        link="${base}"
      else
        link="https://github.com/${ORG}/${repo}/blob/main/docs/adr/${base}"
      fi
      echo "| [${base%.md}](${link}) | ${title} | ${status} | ${tier} |"
    done
    echo
  done
} > "${OUT_FILE}"

echo "Wrote ${OUT_FILE}"
